### ISSUE TITLE
snapshot and stream error

### ISSUE THREAD

**Issue by richardmayo** [hjdhjd/homebridge-unifi-protect2#1]
No matter how hard I try I cant get this to work. Ive installed the camera-ffmpeg plugin and this one. My camera is detected in Homebridge and I can add it to the Home app. But there is no snapshot or stream...

This is my config

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:BE:B9:9A:64:89",
        "port": 53553,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "teal",
            "tempUnits": "c",
            "platform": "config"
        },
        {
            "platform": "Camera-UniFi-Protect",
            "name": "UniFi Protect",
            "controllers": [
                {
                    "url": "https://192.168.1.7:7443/",
                    "username": "homebridge",
                    "password": "xxxxxx"
                }
            ]
        }
    ]
}
```
These are the errors

<img width="659" alt="Screen Shot 2019-08-28 at 7 11 52 PM" src="https://user-images.githubusercontent.com/17880620/63833680-bc84b780-c9c7-11e9-8a79-f03edda11992.png">

**Comment by iiseppi** [comment]
I have this same error. IOS 13.2.1 and homebridge running normal, and cameras can be added normal, but cannot get video from cameras. 
Any advice?

**Comment by hjdhjd** [comment]
I'm just guessing...but it could be that FFMpeg is either not installed or not in the path for homebridge. Try specifying the FFMpeg location...

**Comment by iiseppi** [comment]
Thx for the suggestion! I downloaded newest FFMpeg and installed it into the /usr/local/bin/ and added it to the config: "videoProcessor": "/usr/local/bin/ffmpeg", now it is working.
For some reason, my Apple Watch is not getting snapshot automatically, I have to open live stream first and after live stream it updates the snapshot.

**Comment by kwalkington** [comment]
Did you fix the watch snapshot not updating?

**Comment by iiseppi** [comment]
I installed homebridge to ubuntu and configured all again. With that ”videoProcessor” added to the config snapshots on apple watch are working.
