### ISSUE TITLE
Home App Live Stream is Choppy on iPadOS 17

### ISSUE THREAD

**Issue by dead-beef-cafe** [hjdhjd/homebridge-unifi-protect2#1089]
### Homebridge UniFi Protect Version

7.0.7

### Homebridge Platform and OS

iPad Pro (12.9-inch) (6th generation) / iPadOS 17.5.1

### Homebridge Version

1.8.2

### Node Version

 20.13.1

### UniFi OS Version

3.2.12

### UniFi Protect Controller Version

4.0.33

### Describe the problem

When open a camera live stream in the Home app on my iPad, the full screen video view is choppy with the view only updating around once a second. 

The issue appears to be isolated to the "High" quality stream, while full screen, in the Home app, on iPadOS 17.

If I swipe up with 4 fingers to enter picture in picture mode, the stream works fine. 
If I open the stream in another app (Homedash) the stream works fine (in full screen and windowed)
If I open the stream in the Home app on an older iPad (iPadOS 16), the stream works fine.

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "10.0.1.9",
            "password": "[password]",
            "username": "[user]"
        }
    ],
    "options": [
        "Disable.Doorbell.Messages",
        "Disable.Device.[device1]",
        "Disable.Device.[device2]",
        "Disable.Device.[device3]"
    ],
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
Note: the first stream in the log output is to the Home app, the second is to the 3rd party app Homedash. The first one is choppy, the second works fine.

[12/06/2024, 10:53:00] [UniFi Protect] Front Door [G4 Doorbell]: Streaming request from 10.0.1.186: 1600x1200@30fps, 1,450 kbps. Using 1600x1200@30fps (High) [H264] [RTSP], 3,000 kbps.
[12/06/2024, 10:55:45] [UniFi Protect] Front Door [G4 Doorbell]: Stopped video streaming session.
[12/06/2024, 10:55:48] [UniFi Protect] Front Door [G4 Doorbell]: Streaming request from 10.0.1.186: 1600x1200@30fps, 1,450 kbps. Using 1600x1200@30fps (High) [H264] [RTSP], 3,000 kbps.
[12/06/2024, 10:55:49] [UniFi Protect] Front Door [G4 Doorbell]: Stopped video streaming session.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Try rebooting your iPad and then giving it a go. This isn’t an issue in HBUP I’m afraid. I’ve run into this as well…it’s an iPadOS bug, and it’s been there in varying forms since iPadOS 15 and seems to be a combination of a Home app issue and something in the belly of iPadOS.
