### ISSUE TITLE
Get Verified

### ISSUE THREAD

**Issue by a-rodriguez** [hjdhjd/homebridge-unifi-protect2#14]
I would not consider this a high priority but wanted to suggest making this a "[Verified](https://github.com/homebridge/homebridge/wiki/verified-Plugins)" plugin.

**Comment by hjdhjd** [comment]
Thanks...I’ll look into this when time allows. If someone wants to take this task on and provide whatever changes back, happy to implement. Would be fun.

**Comment by jcvangent** [comment]
Looking at the process, there is not much to do on your end except for asking them to review the plugin:

> How To Request Verification
> If you would like your plugin verified, please open an issue on this repository and fill in the template. The Homebridge project team will then review your plugin and provide constructive feedback if required.
> 
> If you need assistance meeting the verification requirements, please reach out on the Homebridge Discord.

The page to open the issue can be found here: https://github.com/homebridge/verified/issues/new/choose

**Comment by hjdhjd** [comment]
Thanks, I'm aware. Been in the process of dealing with it over the past few weeks. We are verified now.
