### ISSUE TITLE
Unable to Stream UDMP VLAN

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect2#16]
I have a UDMP and the cameras are in a different VLAN. HB see the cameras but I'm getting the following error when try to stream;

`[5/28/2020, 11:25:51 PM] [UniFi Protect] Snapshot from DRIVEWAY at 480:270
[5/28/2020, 11:25:51 PM] [UniFi Protect] An error occurs while making snapshot request
[5/28/2020, 11:25:52 PM] [UniFi Protect] Start streaming video from DRIVEWAY with 640:360@20fps (132kBit)
[5/28/2020, 11:25:52 PM] [UniFi Protect] An error occurs while making stream request
[5/28/2020, 11:25:52 PM] [UniFi Protect] ERROR: FFmpeg exited with code -2`

I'm wondering if the error is because the cameras are in different VLAN or its something else. There is no firewall restrictions between VLANs.

**Comment by hjdhjd** [comment]
Possibly. Also, what OS are you running this on? Newer versions of this plugin have their own ffmpeg on certain OSs (see the fffmpeg-for-homebridge plugin for details). Are you specifying a path to your own ffmpeg?

Finally...try reinstalling the plugin:
```
npm -g uninstall homebridge-unifi-protect2
npm -g --unsafe-perm homebridge-unifi-protect2
```

Let me know.

**Comment by fpuigb** [comment]
I’m running it in Ubuntu 16 server.  I have not tried specifying the path, could you elaborate how to do this?

I will uninstall and install to again to see what happen.

**Comment by fpuigb** [comment]
@hjdhjd - Found the issue, totally my problem not plugin issues. 

The ffmpeg was not installed....:-(

I used the below commands to install it in Ubuntu 16.

`sudo add-apt-repository ppa:mc3man/trusty-media  
sudo apt-get update  
sudo apt-get install ffmpeg  `

**Comment by hjdhjd** [comment]
Glad it helped. :)
