### ISSUE TITLE
No RTSP channel found

### ISSUE THREAD

**Issue by chrispi68** [hjdhjd/homebridge-unifi-protect2#2]
Hi,

During start I get the error Message "No RTSP channel found". RTSP is enabled for 2 of my 5 cameras and for all 3 resolutions. I tested RTSP with VLC and it worked. What am I missing?

Regards
Christoph

**Comment by jaylyerly** [comment]
According to a reddit post I came across recently, this plugin probes all the cameras for RTSP, even if they're not being bridged to HomeKit.  If you enable RTSP on all the cams, I think that will fix it.

**Comment by hjdhjd** [comment]
That's correct. It's an all or nothing proposition at the moment. Perhaps something in the queue to get to at some point, but it's not a priority on my end.
