### ISSUE TITLE
Console spam even after adding cameras

### ISSUE THREAD

**Issue by philipsaad** [hjdhjd/homebridge-unifi-protect2#20]
Not a huge issue, but is is possible to eliminate these messages after the cameras are added to HomeKit?

> [6/15/2020, 12:03:56 PM] Homebridge is running on port 51352.
> [6/15/2020, 12:03:57 PM] Kitchen is running on port 38307.
> [6/15/2020, 12:03:57 PM] Please add [Kitchen] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Front Door Top is running on port 34365.
> [6/15/2020, 12:03:57 PM] Please add [Front Door Top] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Front Foyer is running on port 46191.
> [6/15/2020, 12:03:57 PM] Please add [Front Foyer] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Crib is running on port 46785.
> [6/15/2020, 12:03:57 PM] Please add [Crib] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Living Room is running on port 33095.
> [6/15/2020, 12:03:57 PM] Please add [Living Room] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Dining Room is running on port 36253.
> [6/15/2020, 12:03:57 PM] Please add [Dining Room] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Nursery is running on port 44641.
> [6/15/2020, 12:03:57 PM] Please add [Nursery] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Front Door is running on port 34471.
> [6/15/2020, 12:03:57 PM] Please add [Front Door] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Garage Right is running on port 39119.
> [6/15/2020, 12:03:57 PM] Please add [Garage Right] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Garage Left is running on port 44525.
> [6/15/2020, 12:03:57 PM] Please add [Garage Left] manually in Home app. Setup Code: ***-**-***
> [6/15/2020, 12:03:57 PM] Loft is running on port 39999.
> [6/15/2020, 12:03:57 PM] Please add [Loft] manually in Home app. Setup Code: ***-**-***

And with debug disabled, should we still see the plugin spitting routine use to the console?

> [6/15/2020, 12:09:02 PM] [UniFi Protect] Snapshot from Crib at 480:270
> [6/15/2020, 12:09:02 PM] [UniFi Protect] Snapshot from Front Door at 480:270
> [6/15/2020, 12:09:02 PM] [UniFi Protect] Snapshot from Front Door Top at 480:270
> [6/15/2020, 12:09:02 PM] [UniFi Protect] Snapshot from Dining Room at 480:270

I feel like the console should be silent except to report errors, not warnings or info.

**Comment by hjdhjd** [comment]
Appreciate your aesthetic sensibilities. Unfortunately, they are not my own. :smile: I might do something about this in a future release, but it's not going to be top of mind anytime soon. Stay tuned.
