### ISSUE TITLE
Camera added to home but No Response

### ISSUE THREAD

**Issue by m11rphy** [hjdhjd/homebridge-unifi-protect2#21]
Hi All, 

I have just added your plugin to my hoobs install, yet the camera says no response in home.  could you please help my config is below 

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISWTE6BP3",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-42-434",
        "username": "9A:10:24:B3:AF:E9"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "192.168.1.99",
                    "mac": "78:5D:C8:63:37:D0",
                    "pollingInterval": 10,
                    "keyFile": "~/.hoobs/etc/lgtvKeyFile",
                    "prefsDir": "~/.hoobs/etc/.webosTv",
                    "tvService": true,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "HDMI 1"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "HDMI 2"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "HDMI 3"
                        },
                        {
                            "appId": "com.disney.disneyplus-prod",
                            "name": "Disney Plus"
                        },
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        }
                    ]
                },
                {
                    "name": "My Bedroom TV",
                    "ip": "192.168.1.98",
                    "mac": "78:5D:C8:7D:E9:7D",
                    "pollingInterval": 10,
                    "keyFile": "~/.hoobs/etc/lgtvKeyFile",
                    "prefsDir": "~/.hoobs/etc/.webosTv",
                    "tvService": true,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "HDMI 1"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "HDMI 2"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "HDMI 3"
                        },
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        }
                    ]
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            }
        },
        {
            "platform": "Camera-UniFi-Protect",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect2"
            },
            "name": "UniFi Protect",
            "videoProcessor": "ffmpeg",
            "debugProtect": false,
            "controllers": [
                {
                    "url": "192.168.1.1",
                    "username": "MY NAME",
                    "password": "PASS WORD"
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "cameras": []
        }
    ]
}

**Comment by hjdhjd** [comment]
We can't really help you without a bit more specificity on what the issue is and what you're trying to do. Can you elaborate?

**Comment by pxg14** [comment]
Hi
I have a similar issue. Plugin won't connect to a Dream Machine Pro
These are errors in the log:

[7/2/2020, 23:36:40] [UniFi Protect] Error detecting endpoint type: RequestError: Error: getaddrinfo ENOTFOUND http
[7/2/2020, 23:36:40] [UniFi Protect] Unable to register cameras with HomeKit: TypeError: Cannot read property 'isUnifiOS' of undefined

My config:

{
            "name": "UniFi Protect",
            "videoProcessor": "ffmpeg",
            "debugProtect": false,
            "controllers": [
                {
                    "url": "http://192.168.1.1",
                    "username": "username",
                    "password": "password"
                }
            ],
            "videoConfig": {
                "sourcePrefix": "-re -rtsp_transport tcp",
                "additionalCommandline": "-preset slow -profile:v high -level 4.2 -x264-params intra-refresh=1:bframes=0",
                "mapaudio": "0:0",
                "mapvideo": "0:1",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 20,
                "packetSize": 564,
                "audio": false
            },
            "platform": "Camera-UniFi-Protect"
        }

Thanks

Peter

**Comment by pxg14** [comment]
Hi
No idea why but issue seems to have resolved itself. Restarted homebridge, something I had done numerous times but now I can see Unifi cameras via Homekit.
Thanks
Peter
