### ISSUE TITLE
 Homekit hangs

### ISSUE THREAD

**Issue by ytaf** [hjdhjd/homebridge-unifi-protect2#22]
Hi 

I'm new to all this homebridge stuff so pls excuse me if I am not clear.

I managed to install the api, and managed to see my unifi g3 cameras as accesories within homebridge. When I switched to homekit, I also managed to see these cameras as a favourite accesory. 

However, the problem is homekit hangs almost immediately, when the screen shows a spinning circle on a screen that says "Loading Accessories and Scenes" and no matter how hard I tried, I couldn't change that. 

Does anyone have similar issues and suggestions on how to solve this?

Thanks!

**Comment by hjdhjd** [comment]
This sounds like a problem with ffmpeg streaming on your device. If ffmpeg can't stream out fast enough, HomeKit gets finicky about the stream.

You may want to try adding this to your config.json and see if it helps:

`"additionalCommandline": "-tune zerolatency" `

This option basically sacrifices quality of the video for speed of getting it out to HomeKit.

Another option might be to disable the high quality RTSP stream in UniFi Protect and start off with the lowest quality setting in UniFi Protect.

**Comment by ytaf** [comment]
Thanks! I’ll test this out and revert.
