### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by sparks3875392** [hjdhjd/homebridge-unifi-protect2#23]
Hi, I have two Unifi cameras a G3 Flex and G3 Pro. The image quality doesn't look great especially from the G3 Flex.  

both cameras report the resolution like this:
[UniFi Protect] Start streaming video from Drive UVC G3 Flex with 1280:720@25fps (299kBit).

Should that be 1920x1080? I can't see what to configure to change that. 

Thanks for the plugin.

**Comment by hjdhjd** [comment]
The resolution is mostly driven by HomeKit, unfortunately. It ultimately decides what resolution to pull, we don't. We do generate the highest quality stream we possibly can. There are quite a few updates coming shortly to this plugin...dramatic improvements to the image quality are on my backlog to sort through once I deal with some low-hanging fruit. Stay tuned!
