### ISSUE TITLE
Doorbell aspect ratio off

### ISSUE THREAD

**Issue by Vortec4800** [hjdhjd/homebridge-unifi-protect2#25]
I just added the G4 Doorbell and the image is stretched on both the snapshot and on the video stream. Does this happen with the other cameras too? Is there a way to specify a custom aspect ratio or something for the doorbell?

**Comment by hjdhjd** [comment]
@Vortec4800 - stay tuned. Would love to work with you on this one, but would like to revisit this after a release I have planned for this weekend. It's a rather significant update...would you mind waiting until then to followup?

**Comment by Vortec4800** [comment]
Sure thing. I just finished putting together a home bridge plugin for Ecobee, let me know if I can help somehow.

**Comment by hjdhjd** [comment]
Thanks...pretty covered at the moment. It’s a passion project. Though I don’t have a doorbell handy, so interested in seeing how well it’ll perform in the update that’s coming.

Thanks!

**Comment by Vortec4800** [comment]
Cool, looking forward to checking it out. Frankly it works pretty well even on the current version, just the aspect ratio thing was the only issue I saw. Even audio works!
