### ISSUE TITLE
Re-add previously removed cameras

### ISSUE THREAD

**Issue by WBWBW** [hjdhjd/homebridge-unifi-protect2#26]
I’ve removed a couple cameras directly from HomeKit because I thought I was having issues. Now when I go to “Add Accessory” in HomeKit those two cameras won’t show up. 

What can I do to fix that ? ;)

**Comment by hjdhjd** [comment]
Stay tuned. Big release coming as soon as this weekend that should help this one...in the meantime, you can always manually clear out your homebridge cached accessories and that should do it.
