### ISSUE TITLE
Correct username/password resulting in server error 500 when attempting to retrieve configuration

### ISSUE THREAD

**Issue by bbum** [hjdhjd/homebridge-unifi-protect2#28]
I have a local (limited admin) user on a UDMP + Protect configuration.  Username/password is definitely correct (I purposefully made it incorrect and, as expected, this changes to an auth error).

This repeats ad-nauseum.   I'm happy to grab logs, etc, whatever, but just need a pointer as to where to start.

[8/4/2020, 6:47:04 PM] [UniFi Protect] 10.0.0.1: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[8/4/2020, 6:47:04 PM] [UniFi Protect] Error: 500 - Internal Server Error

**Comment by hjdhjd** [comment]
Thanks @bbum - let me check this against my own UDMP and see if I can replicate. I tested this against a UNVR initially. Will revert in a bit.

**Comment by hjdhjd** [comment]
@bbum Can you check one more thing before I try to recreate this myself on UDMP? What role is assigned to the user you created? You need to ensure it has the Administrator role attached to it so it can both see the cameras and configure RTSP streaming. Thanks!

**Comment by bbum** [comment]
I had the user in the "limited administrative" role.  Now in full super administrator mode.

Actually-- just noticed a different problem.   If I try to log into the user directly on the local LAN, it works to log in.  But clicking on the Protect icon just sits on the protect "loading" icon forever.

This appears to be a Unifi issue.

**Comment by hjdhjd** [comment]
I'll implement an intelligent backoff in a future release. It's on the backlog, but thanks for catching this! Leaving this open for now. Please let me know and revert - and post a link to the issue you mentioned above too please.

**Comment by hjdhjd** [comment]
Backoff implemented in v3.1.0. Enjoy!
