### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by robertgranholm** [hjdhjd/homebridge-unifi-protect2#3]
Great job on the plugin, I'm running homebridge on a 2018 MacMini and got this working no problem, however, there's no audio...is that by design or is there something I can troubleshoot?

**Comment by robertgranholm** [comment]
Hello?

**Comment by ntableman** [comment]
I also get no audio from my g4-pro and have been trying to figure out why

**Comment by robertgranholm** [comment]
The best I can figure is ffmpeg compile, what are you using as a server, I am running on a Mac Mini...but I'm not sure what to change.

**Comment by robertgranholm** [comment]
Recompiled last night...no difference...not sure what to do.

**Comment by hjdhjd** [comment]
This is really an issue with FFMpeg. If you hop onto the UniFI Protect forums at either UBNT or reddit you can find instructions on compiling the right FFMpeg with audio options. This isn't a bug in this plugin I'm afraid. Closing this one out.
