### ISSUE TITLE
Cameras not streaming

### ISSUE THREAD

**Issue by brianmedia** [hjdhjd/homebridge-unifi-protect2#30]
In newest release 3.0.2 the camera tiles update fine every 10 seconds, but the streams won't start. Happens with G3 Flex cameras and doorbell the same

[8/4/2020, 10:31:46 PM] [UniFi Protect] UDMPRO [UDM-PRO] Front [UVC G3 Flex]: Stream quality configured: High.
[8/4/2020, 10:39:31 PM] [UniFi Protect] Front: Starting video stream: 1280x720, 30 fps, 299 kbps.
[8/4/2020, 10:40:01 PM] [UniFi Protect] Front: Stopped video stream.

In Homekit - "No Response - This Camera is not responding"
Then after going back to main Homekit page, the tiles will no longer update.
Once I force quit Homekit, and go back in, the tiles update normally.

This is on iPhone homekit. I ran another test on Apple TV HomeKit and it pulls a 1080p stream and works. vs the iPhone pulling a 720p stream and not working

Worked fine before latest update. No added config, just a straight uninstall/install. Then deleted old cameras from Homekit
UDM Pro - 1.7.2
Protect - 1.14.11

**Comment by tillkruss** [comment]
I'm getting a stream on my iPhone, but not when using macOS's Home app.

**Comment by hjdhjd** [comment]
There's a delay at times in getting a stream. See #29 for more. Can we consolidate on that bug report please? I'm going to close this one.
