### ISSUE TITLE
Camera gone after update

### ISSUE THREAD

**Issue by twynne** [hjdhjd/homebridge-unifi-protect2#31]
Had the previous version of this plugin working fine, and I've read the instructions shared via changelog.  

1. First tried an update of the plugin, then manually checking the config.json and removing the old config block, restarted and could see the camera in Home app but no video.

2. Completely uninstalled the plugin, removed any cameras in HomeKit, restarted.

3. Reinstalled the plugin and entered all config manually.  On restart, the camera no longer appears nor does it appear if I go through 'add accessory' process.

I've repeated 3 now several times, but cannot get the camera itself to reappear in Home app.  Am I missing something?  Is there another place I need to remove the 'old' camera?

Details:

Homebridge:  1.2.0b33
MacOS server (native)
Unifi Protect on UCKG2+

**Comment by hjdhjd** [comment]
@twynne Thanks for the detailed info. What's your camera config on Protect? Also, is the Protect user you have configured have the Administrator role attached to it? You need that so the user can both see the cameras and configure RTSP streaming if needed. Can you check real quick?

**Comment by twynne** [comment]
Hi,

Single camera defined on Protect at this point, and I had already enabled RTSP streaming.  The user configured in the plugin is the sole user defined on Protect, and is defined as admin.

**Comment by twynne** [comment]
Would you have expected the camera to just reappear after the plugin is uninstalled/reinstalled, or would you expect to have to manually 'add accessory' in Home app?  I'm just wondering if there's any possibility that there is a conflict between the device that had already existed in Homekit and the one the plugin is now attempting to add.  I only removed camera devices using Config UI, so if there's somewhere else to check please advise.

**Comment by hjdhjd** [comment]
It's possible. The plugin should auto discover and have the cameras "just show up" in HomeKit with no additional configuration. If you've set it up before using homebridge you may want to validate that it's not an issue by clearing out your accessory cache in Homebridge. I'll look at UDMP and test it out directly later today in the meantime.

**Comment by twynne** [comment]
Should the plugin write anything in terms of what was discovered to the log, as I'm not seeing much beyond the plugin loading.

**Comment by hjdhjd** [comment]
Definitely. You will see a list of all cameras it discovers. If it isn't showing anything it's because it can't see the cameras. What you're basically saying is that it connects to the Protect but isn't seeing any cameras. There's a similar issue reported #28 that may be impacting you and appears to be a Ubiquiti bug. But before that, can you post a couple of things?

- A screenshot showing what roles you have assigned to this user.
- The relevant portion of your config.json
- Any log entries you see related to this plugin

Thanks!

**Comment by twynne** [comment]
Screen attached - it's the only user defined.
![2020-08-05_18-37-39](https://user-images.githubusercontent.com/43317/89445574-4813d600-d74b-11ea-9e49-50fd873cdabf.jpg)

Config.json:

                {
            "debug": false,
            "controllers": [
                {
                    "address": "https://192.168.1.4:7443",
                    "password": "pwd",
                    "username": "user"
                }
            ],
            "platform": "UniFi Protect"
        }

Log:

[8/5/2020, 6:31:44 PM] [UniFi Protect] Initializing UniFi Protect platform...

**Comment by hjdhjd** [comment]
Address is wrong. It's not a URL. Just an IP address that's required.

**Comment by twynne** [comment]
Hmmm... wasn't it URL on the previous release?

Anyway I've just changed it to IP:Port, and now it immediately throws up tons of errors about invalid credentials:

Invalid login credentials given. Please check your login and password.

The userid/password is straight from the Protect web UI.  Does it require something special??  As above, the user has admin.

**Comment by twynne** [comment]
Found it - it didn't want port either!  Seems ok now... will carry on testing.

**Comment by hjdhjd** [comment]
There is detailed documentation detailing how to configure this plugin. Please see the README. Closing this one. :smile:
