### ISSUE TITLE
Request - MAC address ease of use

### ISSUE THREAD

**Issue by matellis** [hjdhjd/homebridge-unifi-protect2#35]
When using the enable & disable features requiring a mac address, it would be super helpful if we could have two features:

1) Accept notation with colons, so we can copy directly from Unifi
2) Log an warning message on startup if Mac address is malformed, i.e. fat fingered and removed a digit by accident

Nice to haves. Thanks.

**Comment by hjdhjd** [comment]
1. I have no intention of supporting colon-based MACs, sorry. The plugin conveniently logs and enumerates all the cameras it knows about, include MAC addresses, in a format it will accept. You can use that if you'd like.

2. LOL. Might add that one...thanks for the feedback.

Good luck.
