### ISSUE TITLE
UVC G3 Flex cameras - won't go live

### ISSUE THREAD

**Issue by nathsea** [hjdhjd/homebridge-unifi-protect2#39]
Hi following the last update the speed is a lot better, thank you. 
I have noticed though that my 2 x UVC G3 Flex cameras don't go live whereas my G3 bullet and dome go live really quickly, settings all seem the same... any ideas?

**Comment by hjdhjd** [comment]
@nathsea Need a lot more information before we can be helpful. Let's start with your specific setup and configuration. What controller are you using (UNVR, UCK, etc?). What's your camera setup? What's your config.json? Does the user you've configured the plugin to use have admin privileges? What version of the plugin are you running?

The above configuration has been working very well for most people to this point, so my suspicion would be this is something specific to your setup.
