### ISSUE TITLE
MQTT documentation contains incorrect documentation for mqtt uri containing a username and password.

### ISSUE THREAD

**Issue by ghenkhaus** [hjdhjd/homebridge-unifi-protect2#47]
The original documentation contains an example `mqtt://user@password:1.2.3.4`, however the correct example should be as follows `mqtt://user:password@1.2.3.4`. I submitted the a PR #46 to resolve the documentation issue.

Hope this helps!

**Comment by hjdhjd** [comment]
Thanks. Closing.
