### ISSUE TITLE
Multiple network interfaces and streaming video

### ISSUE THREAD

**Issue by filibuster007** [hjdhjd/homebridge-unifi-protect2#52]
I might be running into an issue on my system with multiple network interfaces. Would it be possible to include an option to define which network interface to use for streaming to homekit.

A similar option is available in the camera ffmpeg plugin by setting interfaceName in the config.

Would you take this in consideration?

**Comment by hjdhjd** [comment]
There should be better network interface identification in an upcoming release. Stay tuned. I'm aware of camera-ffmpeg, it's a great plugin. 

I have no plans at this time to allow a specific setting of default interfaces, however. The plugin will have improved default interface detection, however.

**Comment by fpuigb** [comment]
I have a similar issue, I can't always live streaming, if I'm in the LAN everything works fine. My HB is running in a VM in a server with two NICs (only one in use) but at this point I'm not sure what is preventing the streaming to establish the live connection when the phone is out of the LAN . I can see the request in the HB dashboard. 

Now with this latest version at least I'm seeing and an error message but I'm still troubleshooting it :-) 

[8/26/2020, 8:45:31 PM] [UniFi Protect] DOORBELL: ffmpeg exited with code: 0 and signal: null (Error)
[8/26/2020, 8:45:31 PM] [UniFi Protect] DOORBELL: Stopped video stream.
[8/26/2020, 8:45:44 PM] [UniFi Protect] DOORBELL: HomeKit video stream request received: 1280x720, 30 fps, 299 kbps.
[8/26/2020, 8:45:55 PM] [UniFi Protect] DOORBELL: Stopped video stream.

@hjdhjd - do you know what port(s) are needed to establish the live streaming?

**Comment by hjdhjd** [comment]
The ports are random and selected by HomeKit.

Start off by ensuring you have no firewalling between the VM, Protect, and the cameras in question. You can progressively play with it from there. I've got an environment with 6 NICs, for what it's worth.

If you've got a doorbell, judging by your logs...disable two-way audio as a starting point.

Closing this one. If you have an issue you'd like to troubleshoot, please open a new, independent, issue. Thanks.
