### ISSUE TITLE
Adding ability for external triggers.

### ISSUE THREAD

**Issue by bls8486** [hjdhjd/homebridge-unifi-protect2#53]
@hjdhjd , Wow.  This is the first and only homebridge plugin that takes full advantage of UniFi.  Great work.

I had a request for enhancement, that is low priority.  Would it be possible to add a parameter to add a switch for external trigger of motion events?  I know not everyone would use this and I agree with your mindset of keeping things simple and hidden unless things are needed.

Here is the scenario:  I have a door contact sensor on my mailbox.  This is right by the street and far out of my motion zones to avoid headlights.  I would like to get an image notification when it is opened.  This way I know if it is the mailman, or my wife has already retrieved the mail.

Again, thank you so much for the hard work and such a polished result.

**Comment by hjdhjd** [comment]
@bls8486 Thanks for the compliment, truly appreciate hearing from people.

So...I'm unlikely to add this, directly. But I may add this indirectly. More on that in a second.

I'd say the core challenge here isn't this plugin, it's your contact sensor. Why not just have a HomeKit-enabled contact sensor and call it a day? That would open up the entire world of HomeKit automation. I do something like this now...Eve makes a fine one.

The indirect way I mentioned: I'm likely to enhance MQTT functionality in the future, and I may add the ability to trigger a motion event via MQTT as part of that in the coming days / weeks.

**Comment by bls8486** [comment]
My apologies. I do have a HomeKit enabled sensor. I poured over the documentation and could see where I could tie it to to trigger the camera notification. My apologies if I missed something.

**Comment by hjdhjd** [comment]
Congrats, you've successfully created an interesting use case. Stay tuned.

**Comment by hjdhjd** [comment]
Feature available in v3.6.0. Enjoy.

**Comment by bls8486** [comment]
I have looked through the documentation but cannot find how to enable this.  How was it implemented?

And thank you for adding it.

**Comment by hjdhjd** [comment]
Well...you're right. :smile:

It is referenced in the Changelog:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#360-2020-09-04

and I've updated the feature option documentation:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/FeatureOptions.md

Take care.
