### ISSUE TITLE
Doorbell contact sensor question. 

### ISSUE THREAD

**Issue by yoko81** [hjdhjd/homebridge-unifi-protect2#55]
Love everything you have done here. Works great. 
So right now if someone presses the doorbell button I get a rich notification on my Apple TV (running the beta and it works great). My question is.... Unless I missed it. Is there a way to get the same notification for motion detection?  I seem to have the problem of %50 of the people decide to knock on the door instead of push the button. So I thought it would be great if there was a way to have motion detection activate the doorbell contact sensor to get the same effect. Not sure if this is possible or if there is a better way to do this. I love getting the snapshot on my Apple TV when some presses the button it’s unobtrusive. Would love it even more if there was a toggle or a way to get it for motion instead or as well. Many thanks.  I also have the G4 doorbell and a Cloudkey Gen2 not sure if that matters.

**Comment by hjdhjd** [comment]
You missed it. :smile:

Go to the motion sensor on iOS and look at it's properties. You can turn on notifications whenever the motion sensor detects motion and you'll receive a rich notification under `Status and Notifications`. You can use it to set schedules, among other things. As to Apple TV - we'll see what iOS 14 and tvOS 14 bring.

Closing this issue. Good luck!
