### ISSUE TITLE
Doorbell message multi-line support

### ISSUE THREAD

**Issue by jonathanbardo** [hjdhjd/homebridge-unifi-protect2#57]
Is there a way to have multi-line on the doorbell? I tried using `\\n` in the config but no luck. It would make up for longer message if it was possible somehow.

**Comment by hjdhjd** [comment]
No. the is a 30 character hard limit, with no special characters allowed by the doorbell. It's not a plugin limitation. Please refer to the documentation for more information: https://github.com/hjdhjd/homebridge-unifi-protect2/blob/master/docs/Doorbell.md#doorbell-messages

Good luck!

**Comment by hjdhjd** [comment]
I should add...you can't use emojis either: https://github.com/hjdhjd/homebridge-unifi-protect2/blob/master/docs/Doorbell.md#some-fun-facts

I'll provide an update to the documentation to make some of these limitations more discoverable. Thanks for raising the issue.

**Comment by jonathanbardo** [comment]
I saw the emoji part. Was just curious if there was a possibility of having newline character but didn't seem like it. Thanks for the quick response :)

**Comment by hjdhjd** [comment]
No worries!
