### ISSUE TITLE
Notifications preferences for Protect cameras in Home app getting reset every time I restart homebridge

### ISSUE THREAD

**Issue by zwily** [hjdhjd/homebridge-unifi-protect2#59]
Hello,

Every time I restart my homebridge process hosting the homebridge-unifi-protect2, my notification preferences for all the cameras get reset to None. This plugin isn't recreating the cameras in HomeKit on every startup is it? It doesn't seem like that, because I don't have to reconfigure them like I did the first time they were added. Any idea what could be causing this?

(Also, this is on iOS 14, so it's possible it could be a bug in the beta.)

Thanks!

**Comment by hjdhjd** [comment]
Sorry, beta versions of iOS aren’t supported I’m afraid.

My notification preferences on two dozen cameras are fine, for what it’s worth, on iOS 13. Suggest you either use a production version of iOS or file a bug report with the iOS team so the rest of us don’t have this bug when iOS 14 hits. :smile:

**Comment by zwily** [comment]
Well after more testing on another device, it appears to happen on iOS 13 too. But it's not necessarily tied to restarting homebridge either, so it's probably just another random HomeKit bug. Thanks for responding so quickly.

**Comment by hjdhjd** [comment]
No worries. My guess would be if you're using the same iCloud account for both iOS 13 and 14, it's an iOS 14 thing. Good luck!
