### ISSUE TITLE
Feature Request: Object Identification from motion event before sending to homekit

### ISSUE THREAD

**Issue by miwagner1** [hjdhjd/homebridge-unifi-protect2#61]
Would be amazing if you could add https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd support since we can not use homekit secure video for object detection.
This way I could get notifications if it was only a person instead of a car on my doorbell.

Or support saving the snapshot to a disk location that I can have Tensorflow watch and send notifications via pushover

**Comment by hjdhjd** [comment]
Thanks for the suggestion. I **won't** be adding any object detection support. I view this as ultimately a likely technical dead end. At some point in the not terribly distant future, I expect we'll all get access to HomeKit Secure Video and that'll provide these more nuanced capabilities. I reserve the right to change my mind too. :smile:

As another avenue, Protect does offer some reasonably fine-grain controls over what triggers a motion event and I find it works nicely...and I have a lot of traffic that can potentially trigger false alarms and I've been able to tune it quite successfully.

As to snapshots...stay tuned. There's something coming soon on that front.

Appreciate the feedback!

**Comment by miwagner1** [comment]
Im using a camera to monitor our reserved parking sports for towing and people walking into it trigger the camera. I look forward to what you are doing with snapshots. As long as I can read them as a file at some point, I can do the rest myself until we gain access too HKSV :D.

**Comment by hjdhjd** [comment]
Fascinating. I think you'll like what I have in mind...

**Comment by durosity** [comment]
> At some point in the not terribly distant future, I expect we'll all get access to HomeKit Secure Video

Gosh I hope you're right.. that plus the doorbell (plus echo cancellation) would basically be the perfect solution for me!  Well.. if Apple ever upgrade HKSV to work with more than.. what is it.. 5? Cameras?

**Comment by fpuigb** [comment]
HKSV needs to be implemented by Ubiquiti only?

**Comment by miwagner1** [comment]
Homebridge needs to implement it at some point if possible. I wonder if Apple is only allowing certified devices to have access to this feature. Ubiquity shows no inclination to adding HomeKit support themselves. My solution is to use https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd and use pushover for the notifications with the snapshot once hjdhjd has the time to implement what he/she has in mind.

**Comment by hjdhjd** [comment]
All of the major homebridge camera plugin developers (yours truly included) are working on it or supporting in various ways. We're making progress...it'll come in fits and starts...but the good news is, we're all collaborating and this is on everyone's radar. Watched pot never boils and all that.

Suffice it to say: @miwagner1 - stay tuned for a few hours re: the above discussion. Next update is almost ready.

**Comment by hjdhjd** [comment]
@miwagner1 v3.6.0 is out. Been working on this one for a while. Read the MQTT documentation and look at the snapshot capabilities in particular. You can pull a snapshot, at will, and get the image via MQTT. I think this will get you what you're looking for.
