### ISSUE TITLE
Error 499 - unknown

### ISSUE THREAD

**Issue by germanhans** [hjdhjd/homebridge-unifi-protect2#62]
This is my first time logging in to the plugin. I am using my actual Unifi username and password ... correct? Every time I try, I know the credentials and IP address are right, but get error 499. I am running beta on UniFi and UniFi protect. Is that the source of the issue? Please advise.

**Comment by hjdhjd** [comment]
Thanks for reaching out. Unfortunately, no beta releases are supported, or will be, in this plugin. That goes for iOS, or UniFi Protect.

Ubiquiti's betas in particular are prone to lots of unforeseen issues...I strongly advise most people to stay away from them for anything beyond curiosity or testing.

My suggestion is that you try a production release of UniFi Protect and see if you still have issues.
