### ISSUE TITLE
HKSV enabled on my G4 doorbell spikes my CPU to 100%

### ISSUE THREAD

**Issue by jfmoots** [hjdhjd/homebridge-unifi-protect2#648]
Just playing with the new HKSV support. Really nice job! 

I have serval G3 domes and one G4 Doorbell. The domes are working perfect but the G4 doorbell spikes my cpu to 100% when I enable it for recording. I notice repeated 566 second recordings being done but failing. It’s like it’s non-stop detecting motion. Any ideas?

**Comment by jfmoots** [comment]
I might be on to something. I now notice that the motion detection in both HomeBridge and the home app shows triggered constantly on that camera. Trying to get it to un-trigger so I can test HKSV again. No idea why it’s constantly triggered. There’s no motion.

**Comment by hjdhjd** [comment]
RTFM. Read the HomeKit Secure Video documentation for the plugin please. Thanks. :smile:

**Comment by jfmoots** [comment]
Got it! @hjdhjd 

i deleted the cache in HomeBridge for that camera. That caused the motion sensor to finally un-trigger. Then when i enabled recording my processor didn’t peg. It looks likes it’s working as expected now. 

No idea why my motion trigger was locked-triggered.

**Comment by bravesfan171** [comment]
@jfmoots I’m having the same issue with one of my G4 Bullets. CPU is pegged between 90 and 100% on my NUC and motion is constantly triggered, along with these errors repeating themselves constantly in the log:
```
[2/13/2022, 7:43:31 PM] [UniFi Protect] Crosbynet [UDM-PRO] Backyard [UVC G4 Bullet]: HomeKit Secure Video event recording ended abnormally: HomeKit canceled the request.
[2/13/2022, 7:46:12 PM] [UniFi Protect] Crosbynet [UDM-PRO] Backyard [UVC G4 Bullet]: FFmpeg failed with error: null: undefined
[HDS ::ffff:192.168.1.229] Delegate finished streaming for 1 without setting RecordingPacket.isLast.         Can't notify Controller about endOfStream!
[HDS ::ffff:192.168.1.229] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[2/13/2022, 7:46:20 PM] [UniFi Protect] Crosbynet [UDM-PRO] Backyard [UVC G4 Bullet]: HomeKit Secure Video has recorded a 11 second motion event.
```
@hjdhjd any ideas? I have tried leaving the default encoder as well as h264_omx and copy

**Comment by hjdhjd** [comment]
Locking this. If you have a problem please use the Discord or open a clean issue. Thanks!
