### ISSUE TITLE
No Response when viewing the cameras over LTE

### ISSUE THREAD

**Issue by miwagner1** [hjdhjd/homebridge-unifi-protect2#65]
The unifi cameras work great over lan.
My logi 2 homekit camera works over LTE
Plugin Version v3.6.0
Node JS v14.9.0

**Comment by hjdhjd** [comment]
Adjust your stream quality to low:

`Enable.StreamOnly.Low`

Does that solve the issue?

**Comment by miwagner1** [comment]
Yes it does.

**Comment by hjdhjd** [comment]
Then you're done. Issue closed. :smile:

Read the Troubleshooting page for more information.
