### ISSUE TITLE
New ffmpeg crash on iphone home

### ISSUE THREAD

**Issue by boot-max** [hjdhjd/homebridge-unifi-protect2#66]
New problem with iPhone on Home -- error produced after updates, does not work. appears on homebridge logs something to to with ffmpeg exited unexpectedly  lots more in logs

**Comment by hjdhjd** [comment]
This isn’t a useful bug report. :smile: I can’t do anything with this I’m afraid.

Please provide a lot more detail about your setup, and information about what you’re doing, and what versions you’re running of Homebridge. There is a hard requirement of Homebridge 1.1.3 starting with 3.6.0 and beyond.

**Comment by boot-max** [comment]
@hjdhjd
> 
> This isn’t a useful bug report. 😄 I can’t do anything with this I’m afraid.
> 
> Please provide a lot more detail about your setup, and information about what you’re doing, and what versions you’re running of Homebridge. There is a hard requirement of Homebridge 1.1.3 starting with 3.6.0 and beyond. 

There is more detail on the UI community forum. I was having a hard time copying the log errors from the screen. Hopefully this will be more useful. When attempting to open doorbell camera you get the following error on the homebridge server now, after the last updates of the app, and the server (happened on same day)  See screen shot. 

![ffmpeg-issue](https://user-images.githubusercontent.com/66483238/92311232-eb3e5200-ef7a-11ea-92c3-1a3f86759a5e.png)

Issue #2  -- Control C -- Copy screen text of log files on homebridge server screen is disabled

**Comment by hjdhjd** [comment]
Thanks.

I'm not sure what you're referring to with respect to support on the "UI forum". If you want support from me, Github is the **only** location I provide support for this plugin.

This error is pretty straightforward - it seems that the installation of ffmpeg is somehow missing.

You have two choices:

1. Completely uninstall this plugin, restart Homebridge, and then reinstall the plugin, and see if that fixes things.

2. Specify a location for ffmpeg in the plugin settings. You can find the setting for location of ffmpeg under the Additional Settings category in the plugin settings Homebridge webUI. It'll be the first entry.

I'd strongly suggest you try option 1 first. That should get things corrected.

Good luck.
