### ISSUE TITLE
Support for Homebridge 1.2.0

### ISSUE THREAD

**Issue by mareknow** [hjdhjd/homebridge-unifi-protect2#68]
Tested latest homebridge-unifi-protect2 ver 1.6.2 with homebridge 1.2.0-beta.35 and snapshots work but streaming fails with:
(node:24593) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/s
rc/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at ProtectStreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-unifi-protect2/src/protect-stream.ts
:222:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insid
e of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate 
the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/
api/cli.html#cli_unhandled_rejections_mode). (rejection id: 265)

Reverted homebridge to ver 1.1.3 and now streaming works as expected.

**Comment by hjdhjd** [comment]
Thanks for the report - **no beta versions of homebridge, iOS, or UniFi Protect are supported**.

This is a bug in the homebridge beta, not this plugin. I'd suggest you report it there. They haven't applied the updates that are in 1.1.3 to the beta tree.

**Comment by hjdhjd** [comment]
FYI - the 1.2 Homebridge beta should be updated to resolve the above now. Good luck.
