### ISSUE TITLE
Is there any way to modify which RTPS stream this plugin uses?

### ISSUE THREAD

**Issue by kinektech-au** [hjdhjd/homebridge-unifi-protect2#9]
As per the title; is there any way to modify/instruct which RTSP this plugin chooses? 

I am experiencing significant lag / delay issues caused by what I think is the plugin automatically going for the highest quality enabled RTSP stream whereas I would prefer it to go for the lowest or medium quality for HomeKit purposes.  

I have yet to try the obvious and switching those higher quality RTSP streams off but I am using them for another project where the higher quality streams is desired. 

Any help is greatly appreciated!

**Comment by hjdhjd** [comment]
The short answer is yes there is, but it’s a bit of work.

The lag you’re detecting, I suspect, has more to do with the horsepower needed for ffmpeg to do it’s thing. If you’re running homebridge on slower or underpowered CPUs, it’s going to struggle.

I’ll look into adding something like this if there’s sufficient need, but it isn’t a priority right now. That said, if you want to do the legwork and take a shot at it...feel free. Happy to incorporate a patch back in.
