### ISSUE TITLE
Cameras unresponsive in Homekit - 'No Response'

### ISSUE THREAD

**Issue by ajcascio** [hjdhjd/homebridge-unifi-protect2#912]
**Describe The Problem:**
 All cameras now show as "No Response"

**To Reproduce:**
 Most likely related to new Homekit Architecture.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**Hoobs on latest release

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:** Hoobs

Will get all versions once I am back on LAN.

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:** 6.4.1
* **UniFi Protect Version:**  v2.7.34
* **UniFi Protect Controller Type:**  UDMP SE
* **UniFi Protect Controller Firmware Version:**  v3.0.18
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14 Pro Max - iOS 16.4.1, iPad Pro 11" 2nd Generation - TBD(Latest)
* **Operating System and OS Version:**  Hoobs via Raspberry Pi4

**Comment by ajcascio** [comment]
Looks like this is exactly what is happening to me. Not sure if I can try same fix in Hoobs enviroment.
https://github.com/hjdhjd/homebridge-unifi-protect/issues/879

**Comment by hjdhjd** [comment]
This isn't an HBUP issue I'm afraid. There's not much I can do to support you here - HBUP is doing what it's supposed to do, and I know that may be of little solace. As @ajcascio suggested, take a look at adjusting the mDNS listener in Homebridge. I don't support HOOBS...feel free to reach out to the HOOBS team for support there. Thanks.
